Repository jenkinsci/influxdb-plugin, pull requests merged in 2020-03, with the labels that each got.

#93 JENKINS-61305 - Fix freestyle jobs using first configured targets
  pom.xml
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublicationService.java
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublisher.java
  src/test/java/jenkinsci/plugins/influxdb/InfluxDbPublisherTest.java
Labels: bug

#94 further SonarQube metrics
  README.md
  src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java
  src/test/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGeneratorTest.java
Labels: enhancement

#82 Extend SonarQube metric keys
  src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java
  src/test/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGeneratorTest.java
Labels: enhancement

#96 Update for SonarQube 8.1
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublicationService.java
  src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java
Labels: maintenance
