Repository jenkinsci/influxdb-plugin, pull requests merged in 2021-03, with the labels that each got.

#110 [JENKINS-63130] - Use Credentials plugin for authentication
  README.md
  doc/img/jenkins-configuration.png
  pom.xml
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublicationService.java
  src/main/java/jenkinsci/plugins/influxdb/models/Target.java
  src/main/resources/jenkinsci/plugins/influxdb/models/Target/config.jelly
  src/test/java/jenkinsci/plugins/influxdb/ConfigurationAsCodeTest.java
  src/test/resources/jenkinsci/plugins/influxdb/ConfigurationAsCodeTest/configuration-as-code.yml
Labels: enhancement

#111 [JENKINS-64999] - Add support for InfluxDB 2.0
  .gitignore
  README.md
  doc/CHANGELOG.md
  doc/available_metrics.md
  doc/breaking_changes.md
  pom.xml
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublicationService.java
  src/main/java/jenkinsci/plugins/influxdb/generators/AbstractPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/ChangeLogPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/CoberturaPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/CustomDataMapPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/CustomDataPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/JUnitPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/JacocoPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/JenkinsBasePointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/PerfPublisherPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/PerformancePointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/PointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/RobotFrameworkPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/generators/serenity/SerenityPointGenerator.java
  src/main/java/jenkinsci/plugins/influxdb/models/Target.java
  src/main/resources/jenkinsci/plugins/influxdb/models/Target/config.jelly
  src/main/resources/jenkinsci/plugins/influxdb/models/Target/help-organization.html
  src/main/resources/jenkinsci/plugins/influxdb/models/Target/help-password.html
  src/main/resources/jenkinsci/plugins/influxdb/models/Target/help-username.html
  src/test/java/jenkinsci/plugins/influxdb/ConfigurationAsCodeTest.java
  src/test/java/jenkinsci/plugins/influxdb/InfluxDbPublisherTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/CustomDataMapPointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/CustomDataPointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/JUnitPointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/JenkinsBasePointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/PerfPublisherPointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/generators/serenity/SerenityPointGeneratorTest.java
  src/test/java/jenkinsci/plugins/influxdb/renderer/ProjectNameRendererTest.java
  src/test/resources/jenkinsci/plugins/influxdb/ConfigurationAsCodeTest/configuration-as-code.yml
Labels: enhancement, maintenance

#113 [JENKINS-65000] - Add support for Robot Framework 4.0
  Jenkinsfile
  doc/available_metrics.md
  pom.xml
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublicationService.java
  src/main/java/jenkinsci/plugins/influxdb/generators/RobotFrameworkPointGenerator.java
Labels: enhancement

#112 JENKINS-65115 Fix JUnit test name to be full name
  doc/available_metrics.md
  doc/breaking_changes.md
  src/main/java/jenkinsci/plugins/influxdb/generators/JUnitPointGenerator.java
Labels: enhancement

#115 Fix FindBugs issue
  src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java
Labels: maintenance

#116 Revert back from using UrlValidator
  pom.xml
  src/main/java/jenkinsci/plugins/influxdb/InfluxDbPublicationService.java
Labels: dependencies

#117 [SonarQube] Reduce pager size to 1 of SONAR_ISSUES_BASE_URL
  src/main/java/jenkinsci/plugins/influxdb/generators/SonarQubePointGenerator.java
Labels: bug
